### ISSUE TITLE
Investigate Slackify errors

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#2999]
This came up because slackify seems to be dropping events from hooks. Not sure if the errors are related or not.

AC:
- [ ] Slackify handles auto work tracking events from hooks and wafflebot
- [ ] The errors are fixed

```
2017-02-22T17:10:53.432433+00:00 app[worker.1]: TypeError: Cannot read property '_id' of undefined
2017-02-22T17:10:53.432450+00:00 app[worker.1]:     at _callee$ (/app/build/webpack:/src/slackifier.ts:41:24)
2017-02-22T17:10:53.432451+00:00 app[worker.1]:     at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:64:40)
2017-02-22T17:10:53.432452+00:00 app[worker.1]:     at GeneratorFunctionPrototype.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:355:22)
2017-02-22T17:10:53.432453+00:00 app[worker.1]:     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:116:21)
2017-02-22T17:10:53.432454+00:00 app[worker.1]:     at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:64:40)
2017-02-22T17:10:53.432455+00:00 app[worker.1]:     at GeneratorFunctionPrototype.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:297:24)
2017-02-22T17:10:53.432455+00:00 app[worker.1]:     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:116:21)
2017-02-22T17:10:53.432456+00:00 app[worker.1]:     at fulfilled (/app/build/index.js:176:32)
2017-02-22T17:10:53.432457+00:00 app[worker.1]:     at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)
2017-02-22T17:10:53.432458+00:00 app[worker.1]:     at wrappedPromise.linkTransaction (/app/node_modules/newrelic/lib/instrumentation/promise.js:273:65)
2017-02-22T17:10:53.432459+00:00 app[worker.1]:     at wrappedPromise.wrapped [as __NR_wrapper] (/app/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)
2017-02-22T17:10:53.432459+00:00 app[worker.1]:     at __NR_wrappedThenHandler (/app/node_modules/newrelic/lib/instrumentation/promise.js:445:26)
2017-02-22T17:10:53.432460+00:00 app[worker.1]:     at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:129:7)
```

**bex note**: We can see if this is resolved with the conversion to knex (needs waffleio/waffle.io-slackify#45)

**Comment by kellihsf** [comment]
PRs connected to issues are working fine. Referencing an issue in a branch name to move the issue to "Work Started" column, isn't being picked up.
